sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm install

script:
  - ng build systelab-charts --prod
  - ng build showcase --prod

after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm -rf systelab.github.io/charts/*
    cp -r dist/showcase/* systelab.github.io/charts
    sed -i -e "s~base href=\"/\"~base href=\"/charts/\"~g" ./systelab.github.io/charts/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
    cd ..
  fi

before_deploy:
  - cp README.md dist/systelab-charts
  - cd dist/systelab-charts

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
