sudo: required
dist: trusty
language: node_js
node_js:
  - 9

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

install:
  - npm install
  - npm install -g karma
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - karma start karma.conf.js --single-run
  - npm run build

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm systelab.github.io/charts/*
    cp dist/* systelab.github.io/charts
    sed -i -e "s~base href=\"/\"~base href=\"/charts/\"~g" ./systelab.github.io/charts/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
  fi

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  on:
    tags: true
